import { useState } from "react";
import { Icon } from "@lastlink/ui";
import type { PublicMemorialPayload } from "@lastlink/shared";
import { card } from "./styles.js";

type Offer = PublicMemorialPayload["offerings"][number];

export function RememberTab({ offers, onOpen }: { offers: Offer[]; onOpen: (id: string) => void }) {
  return <div><div className="mono" style={{ fontSize: 10, color: "var(--ink-3)", letterSpacing: ".12em" }}>THERE IS NO PRESSURE, EVER</div><h2 className="serif" style={{ fontSize: 34, margin: "7px 0 4px" }}>A few thoughtful ways to remember them</h2><p style={{ color: "var(--ink-3)", marginTop: 0 }}>Options selected for this investor demo from LastLink remembrance partners.</p><div className="offering-grid">{offers.map((offer) => <article key={offer.id} style={{ ...card, overflow: "hidden", display: "flex", flexDirection: "column" }}><div style={{ height: 190, background: "var(--brand-grad-soft)" }}>{offer.imageUrl ? <img src={offer.imageUrl} alt="" style={{ width: "100%", height: "100%", objectFit: "cover" }} /> : <div style={{ display: "grid", placeItems: "center", height: "100%" }}><Icon name="heart" size={34} color="var(--brand-purple)" /></div>}</div><div style={{ padding: 20, display: "flex", flexDirection: "column", flex: 1 }}><div className="mono" style={{ fontSize: 9, color: "var(--ink-3)", letterSpacing: ".1em", textTransform: "uppercase" }}>{offer.sponsorLabel ?? "Remembrance partner"}{offer.providerName ? ` · ${offer.providerName}` : ""}</div><h3 className="serif" style={{ fontSize: 24, margin: "8px 0 5px" }}>{offer.title}</h3><p style={{ color: "var(--ink-3)", fontSize: 14, flex: 1 }}>{offer.description}</p><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8 }}><strong style={{ fontSize: 13 }}>{offer.priceLabel}</strong><button className="ll-btn secondary" style={{ padding: "8px 14px" }} onClick={() => onOpen(offer.id)}>{offer.ctaLabel}</button></div></div></article>)}</div></div>;
}

export function OfferingModal({ offer, onClose }: { offer: Offer; onClose: () => void }) {
  const [done, setDone] = useState(false);
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section role="dialog" aria-modal="true" aria-label={offer.title} className="offer-modal" onMouseDown={(e) => e.stopPropagation()}>{offer.imageUrl && <img src={offer.imageUrl} alt="" />}<div style={{ padding: 28 }}>{done ? <><div className="mono" style={{ color: "var(--ok)", fontSize: 10, letterSpacing: ".12em" }}>DEMO PARTNER HANDOFF</div><h2 className="serif" style={{ fontSize: 32, margin: "8px 0" }}>This remembrance is ready.</h2><p style={{ color: "var(--ink-3)" }}>In the funded product, LastLink would now continue securely to {offer.providerName ?? "the remembrance partner"}. No charge or order was created in this demo.</p><button className="ll-btn grad" onClick={onClose}>Return to the memorial</button></> : <><div className="mono" style={{ color: "var(--ink-3)", fontSize: 10, letterSpacing: ".12em" }}>{offer.sponsorLabel ?? "REMEMBRANCE PARTNER"}</div><h2 className="serif" style={{ fontSize: 34, margin: "8px 0" }}>{offer.title}</h2><p style={{ color: "var(--ink-2)", lineHeight: 1.65 }}>{offer.description}</p><div style={{ ...card, padding: 16, margin: "20px 0" }}><div style={{ display: "flex", justifyContent: "space-between" }}><span>{offer.providerName}</span><strong>{offer.priceLabel}</strong></div><div style={{ color: "var(--ink-3)", fontSize: 12, marginTop: 7 }}>A handwritten remembrance note can be included for the family.</div></div><button className="ll-btn grad" style={{ width: "100%", justifyContent: "center" }} onClick={() => setDone(true)}>Continue with this remembrance</button><button style={{ width: "100%", border: 0, background: "none", color: "var(--ink-3)", padding: 13 }} onClick={onClose}>Not now</button></>}</div></section></div>;
}
