// GENERATED by scripts/import-legal-docx.py — do not edit by hand.
// Source: the counsel-supplied .docx. Re-run the script to update.
import type { LegalDoc } from "./types.js";

export const privacy: LegalDoc = {
  "meta": {
    "title": "Privacy Policy",
    "updated": "July 23, 2026",
    "effective": "July 23, 2026"
  },
  "blocks": [
    {
      "k": "callout",
      "runs": [
        {
          "t": "LastLink is built on trust. Our Members share something profoundly personal with us — their final words to the people they love. This Privacy Policy explains exactly what information we collect, how we use it, who we share it with, and the meaningful rights you have over your own information. We will never sell your personal information. We will never use your Legacy Messages for advertising. Your privacy is not a feature — it is the foundation of everything we do."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "This Privacy Policy applies to LastLink, Inc. (\"LastLink,\" \"we,\" \"us,\" or \"our\") and covers information collected through the LastLink platform, website (lastlink.care), mobile applications, and all related services (collectively, the \"Service\"). It applies to Members, Trusted Advocates, recipients of Legacy Messages (Loved Ones), and visitors to our website."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "This Privacy Policy is incorporated into and forms part of our Terms of Service. Terms defined in our Terms of Service have the same meaning here."
        }
      ]
    },
    {
      "k": "h2",
      "n": "1",
      "t": "Information We Collect"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We collect information in three ways: information you give us directly, information generated by your use of the Service, and — in limited circumstances — information from third parties."
        }
      ]
    },
    {
      "k": "h3",
      "n": "1.1",
      "t": "Information You Provide Directly"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "When you create a Legacy Profile, use the Service, or contact us, you may provide:"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Member registration information",
          "b": true
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Full name, email address, phone number, and mailing address"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Date of birth (to verify you are 18 or older)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Identity verification information as required for account setup"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Payment information (processed by our secure payment provider; we do not store full card details)"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Legacy Profile content",
          "b": true
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Legacy Messages — text, audio recordings, video recordings, and photographs you compose for your Loved Ones"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Contact information for your Loved Ones, including names, email addresses, phone numbers, and social media identifiers"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your designated Trusted Advocates' names and contact information"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your preferences for how and to whom each Legacy Message should be delivered"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Health Update information",
          "b": true
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Health Updates submitted by Trusted Advocates on your behalf, including the health status indicator selected (Passing, Facing a Serious Illness, In Hospital Care, In Hospice Care, or Unable to Communicate)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Timestamps and confirmation records associated with Advocacy Confirmations"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Communications with LastLink",
          "b": true
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Emails, support requests, feedback, and other communications you send to us"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Survey responses and research participation (always voluntary)"
        }
      ]
    },
    {
      "k": "h3",
      "n": "1.2",
      "t": "Information Generated by Your Use of the Service"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "When you use the Service, we automatically collect certain technical information:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Log data: IP address, browser type, operating system, pages visited, and timestamps"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Device information: device type, unique device identifiers, and operating system version"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Usage data: features used, actions taken within the platform, and session duration"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Cookies and similar technologies: as described in Section 8 below"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We do not use log data or usage data to analyze the content of your Legacy Messages. Technical data and Legacy Message content are kept strictly separate."
        }
      ]
    },
    {
      "k": "h3",
      "n": "1.3",
      "t": "Information from Third Parties"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We may receive limited information from:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Identity verification services used to confirm your identity at account creation"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Payment processors confirming subscription status"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Trusted Advocates when they submit Health Updates on your behalf"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We do not purchase personal data from data brokers or advertising networks."
        }
      ]
    },
    {
      "k": "h2",
      "n": "2",
      "t": "How We Use Your Information"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We use your information only for the purposes described below. We do not use your personal information for purposes beyond those listed without obtaining your consent."
        }
      ]
    },
    {
      "k": "h3",
      "n": "2.1",
      "t": "To Provide the Service"
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Creating and maintaining your Legacy Profile"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Storing and encrypting your Legacy Messages"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Processing Advocacy Confirmations and releasing Legacy Messages to designated Loved Ones"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Sending notifications to Loved Ones upon Advocacy Confirmation"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Operating and maintaining the Legacy Page"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Processing subscription payments"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Providing customer support"
        }
      ]
    },
    {
      "k": "h3",
      "n": "2.2",
      "t": "To Protect You and Others"
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Verifying your identity to prevent unauthorized access to your Legacy Profile"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Screening Legacy Message content for violations of our Content Standards"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Detecting and preventing fraud, abuse, and security threats"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Maintaining the immutable audit log of Advocacy Confirmations"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Complying with applicable law and responding to lawful requests from public authorities"
        }
      ]
    },
    {
      "k": "h3",
      "n": "2.3",
      "t": "To Improve the Service"
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Analyzing aggregated, anonymized usage data to understand how the platform is used"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Developing new features and improving existing ones"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Conducting internal research on platform reliability and performance"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We do not analyze the content of Legacy Messages for any research or improvement purpose."
        }
      ]
    },
    {
      "k": "h3",
      "n": "2.4",
      "t": "To Communicate with You"
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Sending transactional emails: account confirmations, password resets, payment receipts"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Sending service notices: changes to the platform, Terms, or Privacy Policy"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Sending optional newsletters and product updates (only with your consent; you may unsubscribe at any time)"
        }
      ]
    },
    {
      "k": "h3",
      "n": "2.5",
      "t": "Legal Basis for Processing (EEA & UK Users)"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "If you are located in the European Economic Area or United Kingdom, we process your personal information on the following legal bases:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Contract performance — processing necessary to provide the Service you have requested"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Legitimate interests — fraud prevention, security, platform improvement (balanced against your rights)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Legal obligation — compliance with applicable laws"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Consent — for optional communications and certain cookies (you may withdraw consent at any time)"
        }
      ]
    },
    {
      "k": "h2",
      "n": "3",
      "t": "Legacy Message Privacy — Our Core Commitment"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Your Legacy Messages are the most sensitive information we hold. This section describes the specific protections we apply to them."
        }
      ]
    },
    {
      "k": "h3",
      "n": "3.1",
      "t": "Zero-Access Encryption"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "All Legacy Messages are encrypted using industry-standard encryption both in transit (TLS) and at rest (AES-256). LastLink employees and contractors have no ability to read the content of your Legacy Messages prior to Advocacy Confirmation. Our encryption architecture is designed so that message content is decrypted only at the moment of delivery to designated Loved Ones."
        }
      ]
    },
    {
      "k": "h3",
      "n": "3.2",
      "t": "Strict Access Controls"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Access to systems holding Legacy Message content is restricted to a very small number of senior engineers with a specific operational need. All access is logged, monitored, and subject to regular audit. No employee may access Legacy Message content for any commercial, research, or personal purpose."
        }
      ]
    },
    {
      "k": "h3",
      "n": "3.3",
      "t": "No Advertising Use"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink will never use your Legacy Messages, the identity of your Loved Ones, the details of your health status, or any information about your Passing for advertising, marketing, or commercial profiling purposes. This commitment is absolute and not subject to exception."
        }
      ]
    },
    {
      "k": "h3",
      "n": "3.4",
      "t": "Content Moderation"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Legacy Messages are subject to automated content screening at the time of creation to detect violations of our Content Standards. This screening uses pattern matching and AI-assisted analysis on message content. Human review occurs only where automated screening flags a potential violation, and only for the limited purpose of determining whether delivery should be paused or refused. Content reviewed for moderation purposes is not retained by our moderation team beyond the review period."
        }
      ]
    },
    {
      "k": "h3",
      "n": "3.5",
      "t": "Delivery Records"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "When a Legacy Message is delivered, we retain a delivery record indicating that delivery occurred, the timestamp, and the recipient group (Family, Friends, or Business/Professional). We do not log individual recipient email addresses in delivery records beyond the minimum required for delivery confirmation and retry."
        }
      ]
    },
    {
      "k": "h2",
      "n": "4",
      "t": "How We Share Your Information"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink does not sell your personal information. We do not share your personal information with third parties for their own marketing purposes. We share information only in the circumstances described below."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.1",
      "t": "Service Providers"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We work with trusted third-party service providers who assist us in operating the Service. These providers are contractually prohibited from using your information for any purpose other than providing services to LastLink. Current categories of service providers include:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Cloud infrastructure and data storage (encrypted; providers cannot read message content)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Email and SMS delivery services (receive contact information for Loved Ones for delivery purposes only)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Identity verification services (receive registration information for verification only)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Payment processors (receive payment information; we do not share Legacy Profile content)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Customer support tools (support agents see only information necessary to resolve your issue)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Security and fraud detection services"
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.2",
      "t": "Trusted Advocates"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Your designated Trusted Advocates have access to:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Confirmation that they have been designated as your Trusted Advocate"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "The Health Update submission interface"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Obituary, funeral service, and logistical information that you or they input through the Advocate information portal"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Trusted Advocates do not have access to the content of your Legacy Messages prior to Advocacy Confirmation. They cannot read your messages before delivering them."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.3",
      "t": "Loved Ones"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Upon Advocacy Confirmation, the following information is shared with your designated Loved Ones:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Notification of your Passing via email and/or SMS"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Access to your Legacy Page, including the Legacy Messages you designated for their group"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Obituary, funeral service, and other information input by your Trusted Advocate"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Grief support, legal, funeral, and other resources you or your Trusted Advocate have selected for display"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Loved Ones in one group (e.g., Family) cannot access Legacy Messages designated for another group (e.g., Business/Professional)."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.4",
      "t": "Legal Disclosures"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We may disclose your information if we believe in good faith that disclosure is necessary to:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Comply with applicable law, regulation, or legally binding court order or subpoena"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Respond to a lawful request by a public authority, including law enforcement"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Investigate potential violations of our Terms of Service"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Protect the rights, property, or safety of LastLink, our Members, or the public"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Where legally permitted, we will notify you before disclosing your information in response to a legal process."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.5",
      "t": "Business Transfers"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "If LastLink is involved in a merger, acquisition, financing, or sale of all or substantially all of our assets, your information may be transferred to the successor entity. We will provide notice before your information is transferred and becomes subject to a different privacy policy. In any such transfer, we will require the successor to honor the privacy commitments made in this Policy, including the prohibition on advertising use of Legacy Message content."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.6",
      "t": "With Your Consent"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We may share your information in other circumstances with your explicit prior consent."
        }
      ]
    },
    {
      "k": "h2",
      "n": "5",
      "t": "Health Information — Special Protections"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "The Health Update feature means that LastLink handles sensitive health status information about our Members. We treat this information with the highest level of care."
        }
      ]
    },
    {
      "k": "h3",
      "n": "5.1",
      "t": "HIPAA-Aligned Practices"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "While LastLink may not be a covered entity under the Health Insurance Portability and Accountability Act (HIPAA) in all circumstances, we voluntarily adopt HIPAA-aligned standards for all health status information, including:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "End-to-end encryption of all Health Update submissions"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Strict minimum-necessary access controls"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Immutable audit logging of all access to health status information"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Employee training on health information privacy"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Business Associate Agreement (BAA) availability for B2B partners who are HIPAA covered entities, including hospice organizations, hospitals, and healthcare systems"
        }
      ]
    },
    {
      "k": "h3",
      "n": "5.2",
      "t": "How Health Information Is Used"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Health Update information submitted by Trusted Advocates is used exclusively to:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Determine whether the conditions for Advocacy Confirmation have been satisfied"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Maintain the immutable audit record of the Advocacy Confirmation process"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Display the appropriate health status indicator on the Member's Legacy Page (where the Member has chosen to include this)"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Health status information is never used for advertising, profiling, sale to insurance companies, or any commercial purpose."
        }
      ]
    },
    {
      "k": "h3",
      "n": "5.3",
      "t": "Five Health States"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink's Health Update feature covers five status indicators: Passing (deceased), Facing a Serious Illness, In Hospital Care, In Hospice Care, and Unable to Communicate due to injury. Each status may trigger different notification and delivery actions as configured by the Member. All five states are treated as sensitive health information and subject to the protections in this Section 5."
        }
      ]
    },
    {
      "k": "h2",
      "n": "6",
      "t": "Data Retention"
    },
    {
      "k": "h3",
      "n": "6.1",
      "t": "Active Accounts"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We retain your personal information and Legacy Profile for as long as your account is active. We encourage Members to review and update their Legacy Profile regularly to ensure it remains current."
        }
      ]
    },
    {
      "k": "h3",
      "n": "6.2",
      "t": "Legacy Messages"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Legacy Messages are retained according to your subscription tier:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Free tier: retained for the period specified on the LastLink website, with advance notice before any expiry"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Premium tier: extended or indefinite retention as described on the lastlink.care/pricing page"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "After Advocacy Confirmation and delivery, Legacy Messages remain on your Legacy Page for the period specified in your subscription tier. After that period, they are permanently deleted from our servers."
        }
      ]
    },
    {
      "k": "h3",
      "n": "6.3",
      "t": "Advocacy Confirmation Records"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "The immutable audit log of Advocacy Confirmations is retained for a minimum of 7 years from the date of confirmation. This is necessary for legal and compliance purposes and to respond to any disputes regarding the validity of a confirmation."
        }
      ]
    },
    {
      "k": "h3",
      "n": "6.4",
      "t": "Account Closure"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "When you close your Legacy Profile, we will permanently delete your Legacy Messages and personal information within 30 days, except where retention is required by law or where Advocacy Confirmation records must be retained as described above. We will send you a confirmation when deletion is complete."
        }
      ]
    },
    {
      "k": "h3",
      "n": "6.5",
      "t": "Backup and Recovery"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Deleted information may persist in encrypted backup systems for up to 90 days following deletion from our primary systems before being permanently purged. During this period, the information is not accessible for any operational purpose."
        }
      ]
    },
    {
      "k": "h2",
      "n": "7",
      "t": "Your Privacy Rights"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Depending on where you are located, you may have the following rights regarding your personal information. We honor these rights for all Members, regardless of location."
        }
      ]
    },
    {
      "k": "table",
      "head": [
        "Your Right",
        "What It Means",
        "How to Exercise It"
      ],
      "rows": [
        [
          "Access",
          "Request a copy of the personal information LastLink holds about you",
          "Email privacy@lastlink.care"
        ],
        [
          "Correction",
          "Request that we correct inaccurate or incomplete personal information",
          "Update in your Legacy Profile or email privacy@lastlink.care"
        ],
        [
          "Deletion",
          "Request deletion of your personal information (subject to legal retention requirements)",
          "Close your account or email privacy@lastlink.care"
        ],
        [
          "Portability",
          "Receive your Legacy Messages and personal data in a portable format",
          "Email privacy@lastlink.care with subject: Data Export"
        ],
        [
          "Objection",
          "Object to processing of your personal information for legitimate interest purposes",
          "Email privacy@lastlink.care"
        ],
        [
          "Restriction",
          "Request that we restrict processing of your personal information in certain circumstances",
          "Email privacy@lastlink.care"
        ],
        [
          "Opt-out of marketing",
          "Unsubscribe from optional marketing communications at any time",
          "Use unsubscribe link in any marketing email"
        ],
        [
          "Withdraw consent",
          "Withdraw consent for processing based on consent (does not affect prior processing)",
          "Email privacy@lastlink.care or update account settings"
        ]
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We will respond to all privacy rights requests within 30 days. In complex cases, we may extend this by a further 30 days with notice. We do not charge a fee for privacy rights requests unless they are manifestly unfounded or excessive."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We may need to verify your identity before processing a request. We will not discriminate against you for exercising your privacy rights."
        }
      ]
    },
    {
      "k": "h2",
      "n": "8",
      "t": "Cookies & Tracking Technologies"
    },
    {
      "k": "h3",
      "n": "8.1",
      "t": "What We Use"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink uses cookies and similar technologies to operate the platform, remember your preferences, and understand how the Service is used. We use the following categories:"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Essential cookies:  ",
          "b": true
        },
        {
          "t": "Required for the platform to function. Cannot be disabled. Examples: session management, security tokens, login state."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Functional cookies:  ",
          "b": true
        },
        {
          "t": "Remember your preferences and settings (e.g., language preference). Disabled only if you clear your browser cookies."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Analytics cookies:  ",
          "b": true
        },
        {
          "t": "Aggregated, anonymized data about how the platform is used. Used to improve the Service. No personal identification. You may opt out."
        }
      ]
    },
    {
      "k": "h3",
      "n": "8.2",
      "t": "What We Do Not Use"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink does not use:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Advertising or tracking cookies from third-party ad networks"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Cross-site tracking technologies"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Cookies to build advertising profiles"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Social media tracking pixels"
        }
      ]
    },
    {
      "k": "h3",
      "n": "8.3",
      "t": "Cookie Choices"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You can manage cookie preferences through your browser settings. Disabling essential cookies may prevent the platform from functioning correctly. You may opt out of analytics cookies at any time through your Legacy Profile settings or by contacting privacy@lastlink.care."
        }
      ]
    },
    {
      "k": "h2",
      "n": "9",
      "t": "Data Security"
    },
    {
      "k": "h3",
      "n": "9.1",
      "t": "Security Measures"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink implements administrative, technical, and physical security measures designed to protect your personal information from unauthorized access, disclosure, alteration, and destruction. Our security practices include:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "AES-256 encryption of Legacy Message content at rest"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "TLS encryption for all data in transit"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Multi-factor authentication for all platform accounts and internal systems"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Role-based access controls with minimum-necessary access principles"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Regular penetration testing and security audits"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Continuous monitoring and intrusion detection"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "SOC 2 certification (in progress; see lastlink.care/security for current status)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "HIPAA-aligned administrative safeguards including employee training and access management"
        }
      ]
    },
    {
      "k": "h3",
      "n": "9.2",
      "t": "Data Breach Response"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "In the event of a data breach that poses a risk to your rights and freedoms, we will:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Notify affected Members within 72 hours of becoming aware of the breach, where feasible"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Notify applicable data protection authorities as required by law"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Provide clear information about what happened, what data was affected, and what we are doing in response"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Take immediate steps to contain the breach and prevent further unauthorized access"
        }
      ]
    },
    {
      "k": "h3",
      "n": "9.3",
      "t": "Your Role in Security"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You are responsible for maintaining the confidentiality of your account credentials and for choosing strong, unique passwords. Please contact security@lastlink.care immediately if you suspect unauthorized access to your Legacy Profile."
        }
      ]
    },
    {
      "k": "h2",
      "n": "10",
      "t": "Children's Privacy"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "The LastLink Service is not directed to children under the age of 18. We do not knowingly collect personal information from anyone under 18. If we learn that we have collected personal information from a child under 18, we will delete that information promptly."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "If you believe a child under 18 has provided us with personal information, please contact us at privacy@lastlink.care and we will take appropriate action."
        }
      ]
    },
    {
      "k": "h2",
      "n": "11",
      "t": "International Data Transfers"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink is headquartered in the United States. If you access the Service from outside the United States, your information will be transferred to and processed in the United States and potentially other countries where our service providers operate."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "For users in the European Economic Area, United Kingdom, or Switzerland, we transfer personal data only to countries that provide an adequate level of protection or where appropriate safeguards are in place (such as Standard Contractual Clauses). Please contact privacy@lastlink.care for more information about our transfer mechanisms."
        }
      ]
    },
    {
      "k": "h2",
      "n": "12",
      "t": "Third-Party Links & Resources"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "The LastLink Legacy Page may include links and referrals to third-party services — including funeral providers, grief counselors, legal and estate planning services, insurance providers, and gift delivery services. These resources are provided for the benefit of Loved Ones at a difficult moment."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink is not responsible for the privacy practices of these third-party services. We encourage Loved Ones to review the privacy policies of any third-party service they choose to use. The inclusion of a resource on the Legacy Page does not constitute an endorsement of that service's privacy practices."
        }
      ]
    },
    {
      "k": "h2",
      "n": "13",
      "t": "California Privacy Rights (CCPA / CPRA)"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "If you are a California resident, you have additional rights under the California Consumer Privacy Act (CCPA) and California Privacy Rights Act (CPRA):"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Right to Know:  ",
          "b": true
        },
        {
          "t": "You may request information about the categories of personal information we collect, the purposes for which we use it, and the categories of third parties with whom we share it."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Right to Delete:  ",
          "b": true
        },
        {
          "t": "You may request deletion of your personal information, subject to certain exceptions."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Right to Correct:  ",
          "b": true
        },
        {
          "t": "You may request correction of inaccurate personal information."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Right to Opt Out of Sale:  ",
          "b": true
        },
        {
          "t": "LastLink does not sell personal information. No opt-out is required, but you have this right."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Right to Limit Use of Sensitive Personal Information:  ",
          "b": true
        },
        {
          "t": "You may limit our use of sensitive personal information (including health status data) to purposes strictly necessary to provide the Service."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Right to Non-Discrimination:  ",
          "b": true
        },
        {
          "t": "We will not discriminate against you for exercising your California privacy rights."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "To exercise California privacy rights, contact us at privacy@lastlink.care with the subject line \"California Privacy Rights Request.\" We will respond within 45 days."
        }
      ]
    },
    {
      "k": "h2",
      "n": "14",
      "t": "European Privacy Rights (GDPR)"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "If you are located in the European Economic Area or United Kingdom, the General Data Protection Regulation (GDPR) or UK GDPR applies to our processing of your personal information."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Data Controller:  ",
          "b": true
        },
        {
          "t": "LastLink, Inc., Houston, Texas, United States is the data controller of your personal information."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "EU/UK Representative:  ",
          "b": true
        },
        {
          "t": "We are in the process of appointing an EU/UK representative as required. Contact privacy@lastlink.care for current information."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Supervisory Authority:  ",
          "b": true
        },
        {
          "t": "You have the right to lodge a complaint with your local data protection supervisory authority if you believe we have not handled your personal information in accordance with applicable law."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Our legal bases for processing are described in Section 2.5. For any GDPR-specific inquiry, contact our Data Protection contact at privacy@lastlink.care."
        }
      ]
    },
    {
      "k": "h2",
      "n": "15",
      "t": "Changes to This Privacy Policy"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or other factors. When we make material changes, we will:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Notify you by email to the address associated with your Legacy Profile at least 30 days before the changes take effect"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Display a prominent notice on the LastLink platform"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Update the \"Last updated\" date at the top of this Policy"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We encourage you to review this Policy periodically. Your continued use of the Service after the effective date of changes constitutes acceptance of the updated Policy. If you do not agree to the changes, please close your Legacy Profile before the effective date."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Previous versions of this Privacy Policy are available on request by contacting privacy@lastlink.care."
        }
      ]
    },
    {
      "k": "h2",
      "n": "16",
      "t": "Contact Us — Privacy Questions"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "If you have any questions, concerns, or requests regarding this Privacy Policy or our privacy practices, please contact us:"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Privacy inquiries:  ",
          "b": true
        },
        {
          "t": "privacy@lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "General support:  ",
          "b": true
        },
        {
          "t": "support@lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Security concerns:  ",
          "b": true
        },
        {
          "t": "security@lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Legal matters:  ",
          "b": true
        },
        {
          "t": "legal@lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Partnership (BAA requests):  ",
          "b": true
        },
        {
          "t": "partnerships@lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Website:  ",
          "b": true
        },
        {
          "t": "lastlink.care/privacy"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Mailing address:  ",
          "b": true
        },
        {
          "t": "LastLink, Inc., Attn: Privacy, Houston, Texas, United States"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We take all privacy inquiries seriously and will respond within 30 days. For urgent matters — including suspected unauthorized access to your Legacy Profile — please use the subject line \"URGENT\" and we will respond within 2 business days."
        }
      ]
    }
  ]
};
