// GENERATED by scripts/import-legal-pdf.py — do not edit by hand.
// Source: LastLink_Terms_of_Service_v3_Use this one.docx.pdf
import type { LegalDoc } from "./types.js";

export const terms: LegalDoc = {
  "meta": {
    "title": "Terms of Service",
    "updated": "September 3, 2026",
    "effective": "September 3, 2026"
  },
  "blocks": [
    {
      "k": "callout",
      "runs": [
        {
          "t": "PLEASE READ THESE TERMS OF SERVICE CAREFULLY BEFORE USING LASTLINK. BY CREATING A LEGACY PROFILE, ACTING AS A TRUSTED ADVOCATE, OR ACCESSING ANY LASTLINK SERVICE, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, DO NOT USE LASTLINK.",
          "b": true
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "These Terms of Service (“Terms”) constitute a legally binding agreement between you and LastLink, Inc. (“LastLink,” “we,” “us,” or “our”) governing your use of the LastLink platform, website, and all related services (collectively, the “Service”). These Terms apply to all Linkers, Trusted Advocates, recipients of LastLink Messages, and any other person who accesses the Service."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Quick Summary — What These Terms Cover",
          "b": true
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "This table is a plain-English summary only. The full terms below govern in all cases."
        }
      ]
    },
    {
      "k": "table",
      "head": [
        "Section",
        "Topic",
        "Key point"
      ],
      "rows": [
        [
          "Section 1",
          "Who We Are & Definitions",
          "Key terms used throughout these Terms"
        ],
        [
          "Section 2",
          "Eligibility & Account",
          "You must be 18+ and provide accurate information"
        ],
        [
          "Section 3",
          "The LastLink Service",
          "What LastLink does and how the platform works"
        ],
        [
          "Section 4",
          "LastLink Messages",
          "Your messages are private, encrypted, and released only on passing confirmation"
        ],
        [
          "Section 5",
          "Trusted Advocates",
          "Their role, responsibilities, and limitations"
        ],
        [
          "Section 6",
          "Privacy & Data",
          "How we collect, use, and protect your information"
        ],
        [
          "Section 7",
          "Content Standards",
          "What you may and may not include in LastLink Messages"
        ],
        [
          "Section 8",
          "Subscription & Fees",
          "Free and premium tiers; billing and refunds"
        ],
        [
          "Section 9",
          "Intellectual Property",
          "LastLink owns the platform; you own your messages"
        ],
        [
          "Section 10",
          "Disclaimers",
          "We are not a healthcare, legal, or financial advisor"
        ],
        [
          "Section 11",
          "Limitation of Liability",
          "Our liability is limited as described"
        ],
        [
          "Section 12",
          "Indemnification",
          "You agree to hold LastLink harmless"
        ],
        [
          "Section 13",
          "Termination",
          "Either party may terminate; your messages are handled as described"
        ],
        [
          "Section 14",
          "Governing Law & Disputes",
          "Delaware law; binding arbitration"
        ],
        [
          "Section 15",
          "Changes to These Terms",
          "We will notify you of material changes"
        ],
        [
          "Section 16",
          "Contact Us",
          "How to reach the LastLink team"
        ]
      ]
    },
    {
      "k": "h2",
      "n": "1",
      "t": "Who We Are & Definitions"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink, Inc. is a digital legacy and notification of passing technology company incorporated in the State of Delaware, operating from Houston, Texas. Our platform is protected by United States Patent No. 11,875,417 B1."
        }
      ]
    },
    {
      "k": "h3",
      "n": "1.1",
      "t": "Key Definitions"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"Linker\" (also referred to as \"Member\") means any individual who creates a LastLink Profile on the LastLink platform.",
          "b": true
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"LastLink Profile\" means the account created by a Linker containing their contact lists, LastLink Messages, and Trusted Advocate designations.",
          "b": true
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"LastLink Message\"",
          "b": true
        },
        {
          "t": " means any text, audio, video, photograph, or other content pre-composed by a Linker to be delivered to their Loved Ones upon their Passing."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"Trusted Advocate\" means a person designated by a Linker to confirm the Linker's Passing or health status and thereby authorize the release of LastLink Messages.",
          "b": true
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"Passing\" means the death or incapacitation of a Linker, as confirmed by the Linker's Trusted Advocates through the Advocacy Confirmation process.",
          "b": true
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"Advocacy Confirmation\"",
          "b": true
        },
        {
          "t": " means the process by which two or more Trusted Advocates independently confirm a Linker's Passing or health status, thereby authorizing the release of LastLink Messages."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"Health Update\"",
          "b": true
        },
        {
          "t": " means the health status indicator submitted by a Trusted Advocate, which may include: Passing (deceased), Facing a Serious Illness, In Hospital Care, In Hospice Care, or Unable to Communicate due to injury."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"LastLink Page\"",
          "b": true
        },
        {
          "t": " means the secure, hosted webpage on which a Linker's LastLink Messages are displayed to designated Loved Ones following Advocacy Confirmation."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"Loved Ones\" means the individuals designated by a Linker to receive their LastLink Messages across the Family, Friends, and Business/Professional connection groups.",
          "b": true
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "\"Service\"",
          "b": true
        },
        {
          "t": " means the LastLink platform, website, applications, and all related features and functionality."
        }
      ]
    },
    {
      "k": "h2",
      "n": "2",
      "t": "Eligibility & Account Creation"
    },
    {
      "k": "h3",
      "n": "2.1",
      "t": "Age Requirement"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You must be at least 18 years of age to create a LastLink Profile or serve as a Trusted Advocate. By using the Service, you represent and warrant that you meet this requirement. LastLink does not knowingly collect information from individuals under the age of 18."
        }
      ]
    },
    {
      "k": "h3",
      "n": "2.2",
      "t": "Accurate Information"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You agree to provide accurate, current, and complete information when starting your LastLink Profile and to update that information promptly if it changes. Providing false, misleading, or incomplete information is a violation of these Terms and may result in suspension or termination of your account."
        }
      ]
    },
    {
      "k": "h3",
      "n": "2.3",
      "t": "Account Security"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. You agree to notify LastLink immediately at security@lastlink.care if you become aware of any unauthorized access to your LastLink Profile. LastLink will not be liable for any loss or damage arising from your failure to maintain account security."
        }
      ]
    },
    {
      "k": "h3",
      "n": "2.4",
      "t": "One Account Per Member"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Each Member may maintain only one LastLink Profile. Creating duplicate accounts is prohibited and may result in termination of all associated accounts."
        }
      ]
    },
    {
      "k": "h2",
      "n": "3",
      "t": "The LastLink Service"
    },
    {
      "k": "h3",
      "n": "3.1",
      "t": "What LastLink Provides"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink provides a secure, web-based platform that allows Linkers to:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Create a LastLink Profile and designate Trusted Advocates"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Compose and store LastLink Messages for designated Loved Ones"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Organize Loved Ones into Family, Friends, and Business/Professional groups"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Designate different LastLink Messages for different groups"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Authorize Trusted Advocates to submit Health Updates on their behalf"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Deliver LastLink Messages and notifications to Loved Ones following Advocacy Confirmation"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Provide Loved Ones access to a private, secure LastLink Page"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Access grief support, legal, funeral, and other resources through the LastLink Page"
        }
      ]
    },
    {
      "k": "h3",
      "n": "3.2",
      "t": "The Advocacy Confirmation Process (Patent-Protected)"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "The mechanism by which LastLink Messages are released is protected by United States Patent No. 11,875,417 B1. The Advocacy Confirmation process works as follows:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "A Linker designates two or more Trusted Advocates within their LastLink Profile"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Upon a Linker's Passing or incapacitation, a Trusted Advocate logs into the LastLink platform"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "The Trusted Advocate submits a Health Update confirming the Linker's status"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "A second Trusted Advocate independently confirms the Health Update"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Only after both confirmations are received does LastLink release the Linker's LastLink Messages"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "All Advocacy Confirmations are timestamped and logged in an immutable audit record"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink does not release LastLink Messages based on automated detection, third-party reports, or single-advocate confirmation. Both Trusted Advocates must confirm independently."
        }
      ]
    },
    {
      "k": "h3",
      "n": "3.3",
      "t": "Service Availability"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink targets 99.9% platform uptime. However, we do not guarantee uninterrupted access to the Service. Planned maintenance will be communicated in advance where possible. In the event of a system issue during an active Advocacy Confirmation, LastLink will make every effort to resolve the issue promptly and will notify Trusted Advocates and Members' emergency contacts as appropriate."
        }
      ]
    },
    {
      "k": "h3",
      "n": "3.4",
      "t": "Free and Premium Tiers"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink offers a free tier and one or more premium subscription tiers. Features available on each tier are described on the LastLink website and may change from time to time. LastLink will provide reasonable notice of any changes to tier features."
        }
      ]
    },
    {
      "k": "h2",
      "n": "4",
      "t": "LastLink Messages"
    },
    {
      "k": "h3",
      "n": "4.1",
      "t": "Your Ownership"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You retain full ownership of all LastLink Messages you create. By submitting content to the LastLink platform, you grant LastLink a limited, non-exclusive, royalty-free license to store, process, and deliver your LastLink Messages solely for the purpose of providing the Service. This license terminates when your LastLink Profile is closed."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.2",
      "t": "Privacy & Encryption"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "All LastLink Messages are encrypted at rest and in transit. LastLink staff have zero access to the content of your LastLink Messages prior to Advocacy Confirmation. Your messages are stored in tamper-proof, encrypted object storage and are never accessible by LastLink for any purpose other than delivery upon Advocacy Confirmation."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.3",
      "t": "Public and Private Messages"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Linkers may designate LastLink Messages as:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Public — delivered to all designated Loved Ones simultaneously upon Advocacy Confirmation"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Private — delivered only to the specific Loved One group(s) selected by the Linker (Family, Friends, and/or Business/Professional)"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Private LastLink Messages are accessible only to the designated group(s) and are not visible to other recipients."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.4",
      "t": "Message Formats"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Depending on your subscription tier, LastLink Messages may be submitted in text, audio recording, video recording, and photographic format, subject to storage caps applicable to your tier as described on the LastLink website."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.5",
      "t": "Content Standards"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "All LastLink Messages are subject to the Content Standards set out in Section 7. LastLink reserves the right to refuse delivery of LastLink Messages that violate these standards. See Section 7 for full details."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.6",
      "t": "Message Updates"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Linkers may update, edit, or delete LastLink Messages at any time prior to Advocacy Confirmation. Once Advocacy Confirmation has been completed and messages have been delivered, they cannot be recalled or modified."
        }
      ]
    },
    {
      "k": "h3",
      "n": "4.7",
      "t": "Long-Term Storage"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink will retain LastLink Messages for the period specified in your subscription tier. Premium Linkers receive extended or indefinite storage guarantees as described on the LastLink website. Free tier Linkers will be notified of storage limits and any applicable expiry periods."
        }
      ]
    },
    {
      "k": "h2",
      "n": "5",
      "t": "Trusted Advocates"
    },
    {
      "k": "h3",
      "n": "5.1",
      "t": "Designation"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Linkers must designate a minimum of two Trusted Advocates. A Trusted Advocate must be an adult (18+) who has accepted the role through the LastLink platform. Trusted Advocates may serve in this capacity for multiple Members simultaneously."
        }
      ]
    },
    {
      "k": "h3",
      "n": "5.2",
      "t": "Trusted Advocate Responsibilities"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "By accepting the role of Trusted Advocate, a person agrees to:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Submit a Health Update only when they have genuine personal knowledge of the Linker's Passing or health status"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Act independently — not coordinate with the second Trusted Advocate prior to submitting their confirmation"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Provide accurate and truthful information in all Health Updates"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Notify LastLink promptly if they become unwilling or unable to serve as a Trusted Advocate"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Maintain the confidentiality of any information about the Linker's LastLink Profile"
        }
      ]
    },
    {
      "k": "h3",
      "n": "5.3",
      "t": "Fraudulent Confirmation"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Submitting a false or fraudulent Health Update — including confirming a Passing that has not occurred — is a serious violation of these Terms and may constitute fraud under applicable law. LastLink reserves the right to pursue all available legal remedies against any Trusted Advocate who submits a fraudulent confirmation. LastLink will cooperate fully with law enforcement investigations relating to fraudulent use of the Advocacy Confirmation process."
        }
      ]
    },
    {
      "k": "h3",
      "n": "5.4",
      "t": "Trusted Advocate Limitation of Liability"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Trusted Advocates who act in good faith and in accordance with these Terms are not liable to LastLink, the Linker, or any Loved Ones for the consequences of a Health Update they believed to be accurate at the time of submission."
        }
      ]
    },
    {
      "k": "h3",
      "n": "5.5",
      "t": "Removal of Trusted Advocates"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Linkers may remove and replace Trusted Advocates at any time through their LastLink Profile. Upon removal, the former Trusted Advocate loses all access to the Linker's LastLink Profile. LastLink recommends that Members review their Trusted Advocate designations at least annually."
        }
      ]
    },
    {
      "k": "h2",
      "n": "6",
      "t": "Privacy & Data"
    },
    {
      "k": "h3",
      "n": "6.1",
      "t": "Privacy Policy"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Your use of the Service is also governed by LastLink's Privacy Policy, which is incorporated into these Terms by reference. The Privacy Policy describes how we collect, use, share, and protect your information, including health-related information submitted through the Health Update feature."
        }
      ]
    },
    {
      "k": "h3",
      "n": "6.2",
      "t": "HIPAA Alignment"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink is committed to handling health-related information with the same standards required of covered entities under the Health Insurance Portability and Accountability Act (HIPAA). While LastLink may not be a covered entity under HIPAA in all circumstances, we voluntarily adopt HIPAA-aligned practices including:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "End-to-end encryption of all health status information"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Strict access controls limiting who can view health update data"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Audit logging of all access to health-related information"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Business Associate Agreement (BAA) availability for B2B partners operating as covered entities"
        }
      ]
    },
    {
      "k": "h3",
      "n": "6.3",
      "t": "Data Collected"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink collects information necessary to provide the Service, including:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Member identity and contact information"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "LastLink Message content (stored encrypted; inaccessible to LastLink staff)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Trusted Advocate identity and contact information"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Loved One contact information (email, phone, social media identifiers)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Health Update submissions from Trusted Advocates"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Platform usage data for service improvement"
        }
      ]
    },
    {
      "k": "h3",
      "n": "6.4",
      "t": "Data Retention"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Member data is retained for the period of the Linker's active subscription plus a reasonable period following account closure to allow for dispute resolution. LastLink Message content is deleted from LastLink servers upon a Linker's request or following the applicable storage period. Health Update records are retained as part of the immutable audit log."
        }
      ]
    },
    {
      "k": "h3",
      "n": "6.5",
      "t": "Third-Party Services"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "The LastLink Page may include links and referrals to third-party services including funeral providers, grief counseling services, legal and estate planning resources, insurance providers, and gift delivery services. LastLink is not responsible for the privacy practices or content of third-party services. These resources are provided as a courtesy to Loved Ones and do not constitute an endorsement."
        }
      ]
    },
    {
      "k": "h2",
      "n": "7",
      "t": "Content Standards"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink is committed to ensuring that LastLink Messages are delivered in a dignified, respectful, and lawful manner. By using the Service, you agree that your LastLink Messages and any other content you submit will not:"
        }
      ]
    },
    {
      "k": "h3",
      "n": "7.1",
      "t": "Prohibited Content"
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Contain hate speech, harassment, threats, or content designed to intimidate or harm any individual or group"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Constitute defamation, libel, or slander of any individual or organization"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Include sexually explicit or pornographic content"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Disclose confidential, proprietary, or trade secret information of any third party without authorization"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Violate any applicable law, regulation, or court order"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Constitute fraud or misrepresentation"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Include content that facilitates illegal activity"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Harass, abuse, or threaten any recipient"
        }
      ]
    },
    {
      "k": "h3",
      "n": "7.2",
      "t": "Content Moderation"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink employs AI-assisted content screening and human review to identify LastLink Messages that may violate these Content Standards. Our moderation process is designed to protect recipients without compromising the privacy of Linkers."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "If a LastLink Message is flagged as potentially violating these standards:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "The Member will be notified and given an opportunity to revise the message"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "LastLink may pause delivery of the flagged message pending review"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "In cases of serious violation, LastLink may refuse delivery entirely and notify the Member"
        }
      ]
    },
    {
      "k": "h3",
      "n": "7.3",
      "t": "Your Responsibility"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You are solely responsible for the content of your LastLink Messages. LastLink is not liable for any harm caused by LastLink Message content that violates these standards, and you agree to indemnify LastLink for any claims arising from your content as described in Section 12."
        }
      ]
    },
    {
      "k": "h3",
      "n": "7.4",
      "t": "Dignity Commitment"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink is built on the principle that every person deserves to be remembered with dignity and that every recipient deserves to receive final communications with care and respect. We reserve the right, in our sole discretion, to refuse delivery of any content that we reasonably determine is designed to harm, humiliate, or distress a recipient, even if it does not technically violate the specific prohibitions above."
        }
      ]
    },
    {
      "k": "h2",
      "n": "8",
      "t": "Subscriptions & Fees"
    },
    {
      "k": "h3",
      "n": "8.1",
      "t": "Free Tier"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink offers a free tier that includes account creation, a single LastLink Message, a limited number of Loved One contacts, and a basic LastLink Page. Free tier features are described on the LastLink website and may be updated from time to time."
        }
      ]
    },
    {
      "k": "h3",
      "n": "8.2",
      "t": "Premium Subscriptions"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Premium subscription tiers offer expanded features including multiple LastLink Messages per group, video and audio messages, expanded contact lists, long-term data preservation, and an ad-free LastLink Page experience. Current pricing and features are available at lastlink.care/pricing."
        }
      ]
    },
    {
      "k": "h3",
      "n": "8.3",
      "t": "Billing"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Premium subscriptions are billed on a recurring basis (monthly or annually, as selected). By subscribing, you authorize LastLink to charge your payment method on the applicable billing cycle. All fees are stated in US Dollars and are exclusive of applicable taxes."
        }
      ]
    },
    {
      "k": "h3",
      "n": "8.4",
      "t": "Cancellation & Refunds"
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "You may cancel your premium subscription at any time through your LastLink Profile settings"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Cancellation takes effect at the end of the current billing period — you retain premium access until then"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "LastLink does not provide refunds for partial subscription periods unless required by applicable law"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Upon cancellation, your LastLink Profile reverts to free tier features — LastLink Messages stored within free tier limits are retained"
        }
      ]
    },
    {
      "k": "h3",
      "n": "8.5",
      "t": "Price Changes"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink reserves the right to change subscription prices with 30 days' written notice to current subscribers. If you do not cancel before the effective date of a price change, you authorize LastLink to charge the new price."
        }
      ]
    },
    {
      "k": "h3",
      "n": "8.6",
      "t": "Enterprise & B2B Licensing"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Enterprise licensing, API access, and B2B partnership arrangements are governed by separate written agreements between LastLink and the relevant enterprise partner. Contact partnerships@lastlink.care for information."
        }
      ]
    },
    {
      "k": "h2",
      "n": "9",
      "t": "Intellectual Property"
    },
    {
      "k": "h3",
      "n": "9.1",
      "t": "LastLink's IP"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "The LastLink platform, website, software, design, brand, and all associated technology — including the Advocacy Confirmation workflow protected by United States Patent No. 11,875,417 B1 — are the exclusive intellectual property of LastLink, Inc. These Terms do not grant you any right, title, or interest in LastLink's intellectual property except the limited right to use the Service as described herein."
        }
      ]
    },
    {
      "k": "h3",
      "n": "9.2",
      "t": "Your Content"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You retain all ownership rights to your LastLink Messages and other content you submit to the platform. You grant LastLink a limited license to store, process, and deliver your content solely for the purpose of providing the Service. This license does not grant LastLink the right to use your content for marketing, advertising, or any purpose other than Service delivery."
        }
      ]
    },
    {
      "k": "h3",
      "n": "9.3",
      "t": "Feedback"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "If you provide LastLink with feedback, suggestions, or ideas regarding the Service, you grant LastLink a perpetual, irrevocable, royalty-free license to use such feedback for any purpose without compensation or attribution."
        }
      ]
    },
    {
      "k": "h3",
      "n": "9.4",
      "t": "No Reverse Engineering"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You agree not to reverse engineer, decompile, disassemble, or attempt to derive the source code of any LastLink software. You agree not to circumvent, copy, or replicate the Advocacy Confirmation workflow covered by Patent No. 11,875,417 B1."
        }
      ]
    },
    {
      "k": "h2",
      "n": "10",
      "t": "Disclaimers"
    },
    {
      "k": "h3",
      "n": "10.1",
      "t": "Not Medical, Legal, or Financial Advice"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink is a technology platform. Nothing in the Service, the LastLink Page, or any affiliated resources constitutes medical, legal, estate planning, financial, or grief counseling advice. Any resources available through the LastLink Page are provided for informational purposes only. Members and Loved Ones should consult qualified professionals for advice specific to their circumstances."
        }
      ]
    },
    {
      "k": "h3",
      "n": "10.2",
      "t": "Service \"As Is\""
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "THE SERVICE IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. LASTLINK DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE."
        }
      ]
    },
    {
      "k": "h3",
      "n": "10.3",
      "t": "Delivery Not Guaranteed"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "While LastLink makes every effort to ensure reliable delivery of LastLink Messages, we cannot guarantee delivery in all circumstances, including cases where: (i) a Loved One's contact information has changed; (ii) email or SMS delivery is blocked by the recipient's provider; (iii) a force majeure event affects Service availability. LastLink will make reasonable efforts to retry failed deliveries."
        }
      ]
    },
    {
      "k": "h3",
      "n": "10.4",
      "t": "No Monitoring of Content"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Due to the encrypted nature of LastLink Messages, LastLink does not and cannot routinely monitor message content prior to delivery. Content moderation occurs through automated screening at the time of message creation. LastLink is not liable for LastLink Message content that passes automated screening but subsequently proves to violate these Terms."
        }
      ]
    },
    {
      "k": "h2",
      "n": "11",
      "t": "Limitation of Liability"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, LASTLINK, INC., ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Any indirect, incidental, special, consequential, or punitive damages"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Loss of data, profits, goodwill, or other intangible losses"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Damages arising from unauthorized access to or alteration of your LastLink Profile"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Damages arising from the conduct of any Trusted Advocate"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Damages arising from delays in or failure of LastLink Message delivery"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Damages arising from your reliance on any third-party resources available through the LastLink Page"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "IN NO EVENT SHALL LASTLINK'S TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO LASTLINK IN THE 12 MONTHS PRECEDING THE CLAIM OR (B) ONE HUNDRED US DOLLARS ($100)."
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Some jurisdictions do not allow the exclusion of certain warranties or the limitation of liability for certain types of damages. In such jurisdictions, LastLink's liability is limited to the greatest extent permitted by law."
        }
      ]
    },
    {
      "k": "h2",
      "n": "12",
      "t": "Indemnification"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You agree to defend, indemnify, and hold harmless LastLink, Inc. and its officers, directors, employees, agents, licensors, and service providers from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your violation of these Terms"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your LastLink Message content"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your use of the Service in violation of applicable law"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your role as a Trusted Advocate, including any fraudulent or negligent Health Update"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Any dispute between you and a Loved One or Trusted Advocate"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your infringement of any intellectual property or other rights of any person or entity"
        }
      ]
    },
    {
      "k": "h2",
      "n": "13",
      "t": "Termination"
    },
    {
      "k": "h3",
      "n": "13.1",
      "t": "By You"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You may close your LastLink Profile at any time through your account settings or by contacting support@lastlink.care. Upon closing your account, your LastLink Messages will be permanently deleted from LastLink servers within 30 days, unless applicable law requires a different retention period."
        }
      ]
    },
    {
      "k": "h3",
      "n": "13.2",
      "t": "By LastLink"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink reserves the right to suspend or terminate your access to the Service, with or without notice, if:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "You violate these Terms or any applicable law"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your use of the Service poses a risk to other users, LastLink, or third parties"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your account is inactive for an extended period (LastLink will provide advance notice before closing inactive accounts)"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "LastLink discontinues the Service"
        }
      ]
    },
    {
      "k": "h3",
      "n": "13.3",
      "t": "Effect of Termination"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Upon termination by either party:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Your access to the Service ceases immediately"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "LastLink Messages not yet delivered will not be sent"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "LastLink Messages already delivered to Loved Ones remain on the LastLink Page for the period specified in your subscription tier"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "All accrued payment obligations remain due"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Sections 6, 9, 10, 11, 12, and 14 survive termination"
        }
      ]
    },
    {
      "k": "h3",
      "n": "13.4",
      "t": "Service Discontinuation"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "In the event LastLink discontinues the Service, we will provide Members with at least 180 days' advance notice and will offer Members the opportunity to export their LastLink Messages in a standard format. LastLink will make every effort to ensure that LastLink Messages already stored are delivered in accordance with Member instructions before Service discontinuation."
        }
      ]
    },
    {
      "k": "h2",
      "n": "14",
      "t": "Governing Law & Dispute Resolution"
    },
    {
      "k": "h3",
      "n": "14.1",
      "t": "Governing Law"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "These Terms are governed by the laws of the State of Delaware, without regard to its conflict of law provisions. You consent to personal jurisdiction in the state and federal courts located in the State of Delaware for any disputes not subject to arbitration."
        }
      ]
    },
    {
      "k": "h3",
      "n": "14.2",
      "t": "Binding Arbitration"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "EXCEPT AS DESCRIBED BELOW, ANY DISPUTE ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL BE RESOLVED BY BINDING ARBITRATION UNDER THE RULES OF THE AMERICAN ARBITRATION ASSOCIATION (AAA) IN HOUSTON, TEXAS. THE ARBITRATOR'S DECISION IS FINAL AND BINDING. YOU WAIVE YOUR RIGHT TO A JURY TRIAL."
        }
      ]
    },
    {
      "k": "h3",
      "n": "14.3",
      "t": "Class Action Waiver"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "You agree that any arbitration or proceeding shall be conducted on an individual basis only. You waive any right to bring or participate in a class action, collective action, or representative action."
        }
      ]
    },
    {
      "k": "h3",
      "n": "14.4",
      "t": "Exceptions to Arbitration"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Either party may seek emergency injunctive or other equitable relief in a court of competent jurisdiction to prevent irreparable harm pending arbitration. Claims relating to LastLink's intellectual property, including the patent, are not subject to arbitration."
        }
      ]
    },
    {
      "k": "h3",
      "n": "14.5",
      "t": "Informal Resolution First"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Before initiating arbitration, you agree to contact LastLink at legal@lastlink.care and describe your dispute in writing. LastLink will attempt to resolve the dispute informally within 30 days. If the dispute is not resolved, either party may initiate arbitration."
        }
      ]
    },
    {
      "k": "h2",
      "n": "15",
      "t": "Changes to These Terms"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "LastLink reserves the right to modify these Terms at any time. We will notify you of material changes by:"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Sending an email to the address associated with your LastLink Profile at least 30 days before the effective date"
        }
      ]
    },
    {
      "k": "li",
      "runs": [
        {
          "t": "Displaying a prominent notice on the LastLink platform"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Your continued use of the Service after the effective date of any changes constitutes acceptance of the updated Terms. If you do not agree to the updated Terms, you must close your LastLink Profile before the effective date."
        }
      ]
    },
    {
      "k": "h2",
      "n": "16",
      "t": "Contact Us"
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "If you have any questions, concerns, or feedback regarding these Terms or the Service, please contact us:"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "General support:",
          "b": true
        },
        {
          "t": " support@lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Privacy questions:",
          "b": true
        },
        {
          "t": " privacy@lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Legal matters:",
          "b": true
        },
        {
          "t": " legal@lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Partnership inquiries:",
          "b": true
        },
        {
          "t": " partnerships@lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Mailing address:",
          "b": true
        },
        {
          "t": " LastLink, Inc., Houston, Texas, United States"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "Website:",
          "b": true
        },
        {
          "t": " lastlink.care"
        }
      ]
    },
    {
      "k": "p",
      "runs": [
        {
          "t": "We will respond to all inquiries within 5 business days. For urgent matters relating to an active Advocacy Confirmation or platform emergency, please use the priority support channel available through your LastLink Profile."
        }
      ]
    }
  ]
};
